version: '3'
services:
  app:
    image: 'lemonldap-ng:version:latest'
    container_name: lemon
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8090:9000'
      #- '81:81'
      #- '443:443'
    environment:
          SSODOMAIN: djenkoit.fr
          PORTAL_HOSTNAME: myportal.djenkoit.fr
          MANAGER_HOSTNAME: mymanager.djenkoit.fr
          HANDLER_HOSTNAME: myhandler.djenkoit.fr